---
title: "Deconvolution of MPS STR DNA Mixtures"
author: "Søren B. Vilsen"
date: "`r Sys.Date()`"
header-includes:
    - \usepackage{bm}
    - \usepackage{amssymb}
    - \usepackage{amsmath}
    - \usepackage{amsthm}
    - \usepackage{enumerate} 
output: 
    pdf_document
vignette: >
  %\VignetteIndexEntry{Deconvolution of MPS STR DNA Mixtures}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

\newcommand{\bs}[1]{\ensuremath{\boldsymbol{#1}}}
\newcommand{\mc}[1]{\ensuremath{\mathcal{#1}}}
\newcommand{\mcg}{\ensuremath{g}}

\newcommand{\dst}{\ensuremath{\sim}}
\newcommand{\where}{\ensuremath{ \ | \ }}
\newcommand{\diag}[1]{\ensuremath{\text{diag}\left( #1 \right)}}

\newcommand{\lpnorm}[2]{\ensuremath{||#1||_{#2}}}

\newcommand{\cma}{\ensuremath{\varphi_{ma}}}
\newcommand{\cobs}{\ensuremath{\boldsymbol{\mathcal{C}}_{\text{observed}}}}
\newcommand{\cmis}{\ensuremath{\boldsymbol{\mathcal{C}}_{\text{missing}}}}

\newcommand{\R}{\ensuremath{\mathbb{R}}}
\newcommand{\N}{\ensuremath{\mathbb{N}}}
\newcommand{\Z}{\ensuremath{\mathbb{Z}}}

\newcommand{\p}[1]{\ensuremath{\mathbb{P}\left(#1\right)}}

\newcommand{\E}[1]{\ensuremath{\mathbb{E}\left[#1\right]}}
\newcommand{\Ep}[2]{\ensuremath{\mathbb{E}_{#1}\left[#2\right]}}
\newcommand{\Var}[1]{\ensuremath{\mathbb{V}\text{ar}\left(#1\right)}}
\newcommand{\Cov}[2]{\ensuremath{\mathbb{C}\text{ov}\left(#1, #2\right)}}
\newcommand{\indicator}[1]{\ensuremath{\mathbb{I}\left[#1\right]}}

# Introduction
The central equation to statisticians in forensic genetics is the posterior odds of two competing hypotheses:
\begin{align}
\frac{\p{\mc H_d|\mc E}}{\p{\mc H_p|\mc E}} = \frac{\p{\mc E|\mc H_d}}{\p{\mc E|\mc H_p}}\frac{\p{\mc H_d}}{\p{\mc H_p}}
\end{align}
where $\mc E$ is the evidence (quantitative and qualitative), $\mc H_d$, and $\mc H_p$ are the hypotheses of the defence and prosecution, respectively, $\p{\mc E|\mc H_d}/\p{\mc E|\mc H_p}$ is the likelihood ratio of the evidence under the two hypotheses, and $\p{\mc H_d}/\p{\mc H_p}$ are the prior odds of the hypotheses. We cannot and should not infer the prior odds, they should be determined by the court, which leaves the likelihood ratio:
\begin{align}
LR(\mc H_d, \mc H_p) = \frac{\p{\mc E|\mc H_d}}{\p{\mc E|\mc H_p}}.
\end{align}

Assuming that the evidence $\mc E$ consists of quantitative information $\mc Q$ (the coverage in MPS or peak height/area in CE) about genetic information $\mcg$, then we can factorise $\p{\mc E|\mc H_i}$ as: 
\begin{align}
\p{\mc E|\mc H_i} = \p{\mc Q, \mcg|\mc H_i} = \p{\mc Q|\mcg}\p{\mcg|\mc H_i}.
\end{align}

Thus, the probability of the evidence, given a hypothesis, as two parts: 
\begin{enumerate}[(1)]
\item \textbf{The probability of the quantitative information given allelic information}, determinded by the likelihood under a model.
\item \textbf{The probability of the allelic information under the hypothesis in question}, assuming either HWE or $\theta$ correction \cite{Balding1994}.
\end{enumerate}

Let $\mc U_p$ and $\mc U_d$ be the set of unknown profiles under the prosecutors and defence hypotheses, respectively, then we can generally write the $LR$ as:
\begin{align}
LR(\mc H_d, \mc H_p) = \frac{\displaystyle\sum_{\bs \mcg_{U_d} \in \mc U_d} L\left(\bs{\mc Q}|\bs \mcg_{K_d}, \bs \mcg_{U_d}\right)\p{\bs \mcg_{U_d}|\bs \mcg_{K}}}{\displaystyle\sum_{\bs \mcg_{U_p} \in \mc U_p} L\left(\bs{\mc Q}|\bs \mcg_{K_p}, \bs \mcg_{U_p}\right)\p{\bs \mcg_{U_p}|\bs \mcg_{K}}}, \label{eq:generalWoE}
\end{align}
where $\bs \mcg_{K} = \{\bs \mcg_{K_d}, \bs \mcg_{K_p}\}$.

The sums in the numerator and denominator of a general $LR$, as seen in Eq.\ \eqref{eq:generalWoE}, may be intractable. In order to get around this problem we will approximate the $LR$ by searching through the space of unknown genotypes (given a hypothesis) using an Evolutionary Algorithm.

In the remainder of these notes, we will assume the following (unless otherwise stated):
\begin{enumerate}[(1)]
\item We have sequenced a sample using an $M$ marker multiplex panel and denote an arbitrary locus by $m$. 
\item We have observed $A_m$ alleles at locus $m$ and denote an allele (represented as sequenced DNA strings in MPS) by $a \in \{a_{m1}, ..., a_{mA_m}\}$.
\item The DNA sample is a mixture of $C$ DNA profiles, i.e.\ that the sample contains exactly $C$ contributors.
\end{enumerate}

# The coverage model
The model was introduced in [@vilsen2017c]

